name: AdvancedReplay
version: ${project.version}
main: me.jumper251.replay.ReplaySystem
author: Jumper251
depend: [ProtocolLib]
commands:
  replay:
    description: Main Replay command
    aliases: [rp]
    permission: replay.command